language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update -qq

install:
  - sudo apt install -qq g++-6 libboost-all-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake ..
  - make

