language: cpp
compiler: gcc
dist: xenial

git:
  depth: false

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update -qq

install:
  - sudo apt install -qq g++-7 libboost-all-dev

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++-7
  - make

